name: ZAR
favicon: null
layout_spectrum: 0.1660217926837504
typography_spectrum: 0.34369481657631695
title: ZAR.INK
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4e4'
    - '#bdad81'
    - '#252525'
    - '#6a594f'
    - '#74d5f7'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
